#!C:\Users\user\Desktop\Ai_keystroke_typing-_sound\my_env3.10\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
